application:
  otel:
    memory-exporter: true
  name: template
  instance: template-01

redis:
  host: localhost
  port: 6379

server:
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.export.otlp.OtlpMetricsExportAutoConfiguration
  datasource: # change this configurations to your database
    url: jdbc:postgresql://localhost:5434/template
    username: postgres
    password: 123456
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  tracing:
    enabled: false
  metrics:
    export:
      otlp:
        enabled: false

#otel:
#  sdk:
#    disabled: true

# otel:
#   exporter:
#     otlp:
#       endpoint: http://localhost:4318
#       compression: gzip
